import { describe, expect, it } from 'vitest';
import parity from './brew-parity.json';
import {
  BoardRandom,
  BrewBoard,
  BrewGame,
  BURN_TICKS,
  BURNT,
  HEAVY,
  LIGHT,
  MEDIUM,
  SPICE,
  TICK_MS,
  WARNING_TICK,
  type FurnaceEvent,
} from './logic';

/** A board with the given columns (left to right, top to bottom). */
function boardOf(columns: number[][]): BrewBoard {
  const board = new BrewBoard(0);
  board.columns = columns.map((c) => [...c]);
  return board;
}

const tall = (piece: number) => new Array(9).fill(piece);
const short = (piece: number) => new Array(8).fill(piece);
/** Ten alternating columns of mediums, with column 9 replaced. */
function withRightColumn(column: number[]): BrewBoard {
  const cols = Array.from({ length: 10 }, (_, x) => (x % 2 === 0 ? tall(MEDIUM) : short(MEDIUM)));
  cols[9] = column;
  return boardOf(cols);
}

describe('BoardRandom', () => {
  it('matches java.util.Random', () => {
    // new Random(42).nextInt() is -1170105035.
    expect(new BoardRandom(42).next(32)).toBe(-1170105035);
    // new Random(0).nextInt(10) twice: 0, 8.
    const r = new BoardRandom(0);
    expect([r.nextInt(10), r.nextInt(10)]).toEqual([0, 8]);
  });
});

describe('parity with reference fixtures BrewBoard', () => {
  // Generated by scripts/parity/BrewParity.java against the real game classes.
  for (const game of parity as { seed: string; start: number[][]; steps: { swaps: number[][]; distilled: boolean; r: number[]; board: number[][] }[] }[]) {
    it(`seed ${game.seed}`, () => {
      const board = new BrewBoard(BigInt(game.seed));
      expect(board.columns).toEqual(game.start);
      for (const step of game.steps) {
        for (const [x1, y1, x2, y2] of step.swaps) expect(board.swap(x1, y1, x2, y2)).toBe(true);
        const result = board.scoreRightColumn();
        board.addNextColumn();
        expect(result.distilled).toBe(step.distilled);
        expect([result.lights, result.mediums, result.heavies, result.spices]).toEqual(step.r.slice(0, 4));
        expect(result.score).toBe(step.r[4]);
        expect(result.bonus).toBe(step.r[5]);
        expect(board.columns).toEqual(step.board);
      }
    });
  }
});

describe('BrewBoard', () => {
  it('starts with the furnace column all black and tall even columns', () => {
    const board = new BrewBoard(5);
    expect(board.columns[9]).toEqual(short(HEAVY));
    for (let x = 0; x < 10; x++) expect(board.columns[x].length).toBe(x % 2 === 0 ? 9 : 8);
    // The first 17 pieces made (columns 8 and 7) never include spice.
    expect([...board.columns[8], ...board.columns[7]]).not.toContain(SPICE);
  });

  it('swaps in a cycle: white rises past black, brown past white, black past brown', () => {
    // Column 0 is tall, column 1 short: (0,y) sits above (1,y), and (1,y) above (0,y+1).
    const board = boardOf([[HEAVY, ...tall(MEDIUM).slice(1)], [LIGHT, ...short(MEDIUM).slice(1)], ...Array.from({ length: 8 }, (_, i) => (i % 2 === 0 ? tall(MEDIUM) : short(MEDIUM)))]);
    // Black above white: the white rises.
    expect(board.isSwappable(0, 0, 1, 0)).toBe(true);
    expect(board.swap(1, 0, 0, 0)).toBe(true);
    expect(board.columns[0][0]).toBe(LIGHT);
    expect(board.columns[1][0]).toBe(HEAVY);
    // Now white above black: no swap back.
    expect(board.isSwappable(0, 0, 1, 0)).toBe(false);
    // White above brown: the brown rises.
    board.columns[1][0] = MEDIUM;
    expect(board.isSwappable(1, 0, 0, 0)).toBe(true);
    // Brown above black: the black rises.
    board.columns[0][0] = MEDIUM;
    board.columns[1][0] = HEAVY;
    expect(board.isSwappable(0, 0, 1, 0)).toBe(true);
    // Same type, or anything with spice: never.
    board.columns[1][0] = MEDIUM;
    expect(board.isSwappable(0, 0, 1, 0)).toBe(false);
    board.columns[1][0] = SPICE;
    expect(board.isSwappable(0, 0, 1, 0)).toBe(false);
    // Burnt whites swap like whites.
    board.columns[0][0] = HEAVY;
    board.columns[1][0] = BURNT;
    expect(board.isSwappable(0, 0, 1, 0)).toBe(true);
  });

  it('only swaps with diagonal neighbours in the next column', () => {
    const board = new BrewBoard(1);
    expect(board.isAdjacent(0, 3, 0, 4)).toBe(false);
    expect(board.isAdjacent(0, 3, 1, 3)).toBe(true);
    expect(board.isAdjacent(0, 3, 1, 2)).toBe(true);
    expect(board.isAdjacent(0, 3, 1, 4)).toBe(false);
    expect(board.isAdjacent(1, 3, 0, 4)).toBe(true);
    expect(board.neighbour(0, 0, 0)).toBeNull();
    expect(board.neighbour(0, 0, 3)).toEqual([1, 0]);
    expect(board.neighbour(1, 7, 3)).toEqual([2, 8]);
  });

  it('scores Crystal Clear, with a growing bonus in a row', () => {
    const board = withRightColumn(short(LIGHT));
    const first = board.scoreRightColumn();
    expect(first).toMatchObject({ distilled: true, verdict: 'clear', score: 8, bonus: 0, streak: 0 });
    const second = board.scoreRightColumn();
    expect(second).toMatchObject({ verdict: 'clear', bonus: 4, streak: 2 });
    const third = board.scoreRightColumn();
    expect(third).toMatchObject({ bonus: 8, streak: 3 });
    // Spice keeps a column Crystal Clear.
    board.columns[9] = [SPICE, ...short(LIGHT).slice(1)];
    expect(board.scoreRightColumn()).toMatchObject({ verdict: 'clear', spice: 'spicy', score: 10, bonus: 12, streak: 4 });
    board.columns[9] = [MEDIUM, ...short(LIGHT).slice(1)];
    expect(board.scoreRightColumn()).toMatchObject({ verdict: 'smooth', bonus: 0 });
    expect(board.consecCrystal).toBe(0);
  });

  it('calls a column Smooth, Blecch, plain or Burnt by its mix', () => {
    const verdict = (column: number[]) => withRightColumn(column).scoreRightColumn();
    expect(verdict([0, 0, 0, 0, 0, 1, 1, 1])).toMatchObject({ verdict: 'smooth', score: 5 });
    expect(verdict([0, 0, 0, 0, 1, 1, 1, 1])).toMatchObject({ verdict: null, distilled: true });
    expect(verdict([0, 0, 0, 0, 2, 2, 2, 2])).toMatchObject({ verdict: 'blecch', distilled: true, score: 0 });
    expect(verdict([0, 0, 0, 0, 0, 2, 2, 1])).toMatchObject({ verdict: null, distilled: true, score: 3 });
    expect(verdict([0, 0, 0, 2, 2, 2, 2, 3])).toMatchObject({ verdict: 'burnt', distilled: false, spice: 'wasted_spice', score: -3 });
    expect(verdict([2, 2, 2, 2, 2, 2, 2, 2])).toMatchObject({ verdict: null, distilled: false, score: 0 });
    // A burnt white counts against the column like a black when scored, and costs 3.
    expect(verdict([4, 0, 0, 0, 0, 1, 1, 1])).toMatchObject({ verdict: null, distilled: true, heavies: 1, score: 1 });
  });

  it('turns every two burned whites into a burnt white', () => {
    const board = withRightColumn([0, 0, 0, 2, 2, 2, 2, 2]);
    board.scoreRightColumn();
    expect(board.discardedLights).toBe(3);
    let next = LIGHT;
    board.pickPiece = () => next;
    expect(board.nextPiece()).toBe(BURNT);
    expect(board.discardedLights).toBe(1);
    expect(board.nextPiece()).toBe(LIGHT);
    next = HEAVY;
    expect(board.nextPiece()).toBe(HEAVY);
  });
});

describe('BrewGame', () => {
  function run(game: BrewGame, until: number): FurnaceEvent[] {
    return game.update(until);
  }

  it('warns at tick 40 and burns on the 50th tick', () => {
    const game = new BrewGame(3, 0);
    const warn = run(game, TICK_MS * (WARNING_TICK + 1));
    expect(warn).toEqual([{ type: 'warning' }]);
    expect(run(game, TICK_MS * BURN_TICKS)).toEqual([]);
    const burn = run(game, TICK_MS * (BURN_TICKS + 1));
    expect(burn.map((e) => e.type)).toEqual(['burn']);
    expect(game.furnace).toBe(0);
    expect(game.furnaceLevel()).toBe(59);
  });

  it('holds a due burn until swaps finish', () => {
    const game = new BrewGame(3, 0);
    game.setSettled(false);
    expect(run(game, TICK_MS * (BURN_TICKS + 3)).filter((e) => e.type === 'burn')).toEqual([]);
    expect(game.furnaceLevel()).toBe(10);
    const events = game.setSettled(true);
    expect(events.map((e) => e.type)).toEqual(['burn']);
  });

  it('burns on request and restarts the clock', () => {
    const game = new BrewGame(3, 0);
    expect(game.burnNow(1000).map((e) => e.type)).toEqual(['burn']);
    expect(game.furnace).toBe(0);
    expect(run(game, 1000 + TICK_MS - 1)).toEqual([]);
  });

  it('ends after 100 pieces go in the jug, unless on a 12+ Crystal Clear streak', () => {
    const game = new BrewGame(3, 0);
    game.board.pickPiece = () => LIGHT;
    // Fill the board with whites so every column distils Crystal Clear.
    game.board.columns = game.board.columns.map((c) => c.map(() => LIGHT));
    let burns = 0;
    while (!game.finished && burns < 30) {
      game.burnNow(burns);
      burns++;
    }
    // 12 columns get past 100 pieces, but the 12th in a row keeps going: it ends on the 12th Crystal Clear only if
    // the streak shown is under 12, so with every column clear it runs until a non-clear column.
    expect(game.finished).toBe(false);
    game.board.columns[9] = game.board.columns[9].map(() => MEDIUM);
    game.burnNow(100);
    expect(game.finished).toBe(true);
  });

  it('ends at 100 pieces without a streak', () => {
    const game = new BrewGame(3, 0);
    game.board.pickPiece = () => MEDIUM;
    game.board.columns = game.board.columns.map((c) => c.map(() => MEDIUM));
    let burns = 0;
    while (!game.finished) game.burnNow(burns++);
    expect(burns).toBe(12);
    expect(game.distilled).toBe(102);
  });
});

describe('practice extras', () => {
  it('captures junk remaining at the first Crystal Clear, excluding whites, spices and the replacement', () => {
    const game = new BrewGame(3, 0, { endless: true });
    game.board.pickPiece = () => HEAVY;
    // A burnt column must not capture the stat.
    game.board.columns = game.board.columns.map((column) => column.map(() => LIGHT));
    game.board.columns[9] = game.board.columns[9].map(() => HEAVY);
    game.burnNow(0);
    expect(game.junkLeft).toBeNull();
    // Include each type of junk and spices among the nine columns that will remain.
    game.board.columns = game.board.columns.map((column) => column.map(() => LIGHT));
    game.board.columns[0] = [MEDIUM, HEAVY, BURNT, SPICE, LIGHT, LIGHT, LIGHT, LIGHT];
    game.board.columns[1][0] = SPICE;
    game.board.columns[9][0] = SPICE; // A spicy Crystal Clear still captures the stat.
    game.burnNow(1);
    expect(game.junkLeft).toBe(3);
    expect(game.board.columns[0].every((piece) => piece === HEAVY)).toBe(true);
    // Later Crystal Clears, including a new chain, must retain the original count.
    game.burnNow(2);
    expect(game.junkLeft).toBe(3);
    game.board.columns[9] = game.board.columns[9].map(() => MEDIUM);
    game.burnNow(3);
    game.board.columns[9] = game.board.columns[9].map(() => LIGHT);
    game.burnNow(4);
    expect(game.junkLeft).toBe(3);
    expect(new BrewGame(3, 0).junkLeft).toBeNull();
  });

  it('retains a zero junk count after the first Crystal Clear', () => {
    const game = new BrewGame(3, 0, { endless: true });
    game.board.columns = game.board.columns.map((column) => column.map(() => LIGHT));
    game.board.pickPiece = () => HEAVY;
    game.burnNow(0);
    expect(game.junkLeft).toBe(0);
    game.burnNow(1);
    expect(game.junkLeft).toBe(0);
  });

  it('keeps the longest crystal chain after a break and a shorter chain', () => {
    const game = new BrewGame(3, 0, { endless: true });
    expect(game.longestCrystalChain).toBe(0);
    const burn = (piece: number) => {
      game.board.columns[9] = game.board.columns[9].map(() => piece);
      game.burnNow(0);
    };
    burn(LIGHT);
    expect(game.longestCrystalChain).toBe(1);
    burn(LIGHT);
    burn(LIGHT);
    expect(game.longestCrystalChain).toBe(3);
    burn(MEDIUM);
    expect(game.board.consecCrystal).toBe(0);
    burn(LIGHT);
    burn(LIGHT);
    expect(game.longestCrystalChain).toBe(3);
    burn(LIGHT);
    burn(LIGHT);
    expect(game.longestCrystalChain).toBe(4);
    expect(new BrewGame(3, 0).longestCrystalChain).toBe(0);
  });

  it('pauses the furnace clock', () => {
    const game = new BrewGame(3, 0);
    game.update(TICK_MS * 10);
    expect(game.furnace).toBe(10);
    game.pause(TICK_MS * 10);
    game.update(TICK_MS * 100);
    expect(game.furnace).toBe(10);
    game.resume(TICK_MS * 100);
    game.update(TICK_MS * 105);
    expect(game.furnace).toBe(15);
  });

  it('runs a custom timer, no timer, or forever', () => {
    const quick = new BrewGame(3, 0, { tickMs: 100 });
    expect(quick.update(100 * 50).map((e) => e.type)).toContain('burn');
    const none = new BrewGame(3, 0, { timerless: true });
    expect(none.update(1e9)).toEqual([]);
    expect(none.burnNow(5).map((e) => e.type)).toEqual(['burn']);
    const endless = new BrewGame(3, 0, { endless: true });
    endless.board.pickPiece = () => MEDIUM;
    endless.board.columns = endless.board.columns.map((c) => c.map(() => MEDIUM));
    for (let i = 0; i < 20; i++) endless.burnNow(i);
    expect(endless.finished).toBe(false);
    expect(endless.distilled).toBeGreaterThan(150);
  });
});
