import { describe, expect, it } from 'vitest';
import parity from './forage-parity.json';
import { BoardRandom, CratePoints, ForageBoard, HEIGHT, makeAnts, makeCrate, WIDTH } from './board';
import { Forage, TIMING } from './engine';

interface ParityMove {
  x: number;
  y: number;
  ccw: boolean;
  bonus: number;
  outcome: 'illegal' | 'same' | 'moved';
  points: number;
  combo: number;
  crates: number;
  area: number;
  pending: number;
  collected: number;
  board?: number[];
}

describe('BoardRandom', () => {
  it('matches java.util.Random', () => {
    expect(new BoardRandom(42).next(32)).toBe(-1170105035);
    const r = new BoardRandom(0);
    expect([r.nextInt(10), r.nextInt(10)]).toEqual([0, 8]);
    // new Random(7).nextFloat()
    expect(new BoardRandom(7).nextFloat()).toBeCloseTo(0.730699, 6);
  });
});

describe('parity with reference fixtures', () => {
  // Generated by scripts/parity/ForageParity.java, which plays random games on the real game's
  // ForageBoard and drop-engine classes.
  for (const game of parity as { seed: string; difficulty: number; start: number[]; moves: ParityMove[] }[]) {
    it(`seed ${game.seed}, difficulty ${game.difficulty}`, () => {
      let bonus = 0;
      const forage = new Forage(BigInt(game.seed), { beforeMove: (g) => bonus && (g.board.bonusMode = bonus) }, game.difficulty);
      expect(forage.cells).toEqual(game.start);
      game.moves.forEach((move, i) => {
        bonus = move.bonus;
        const outcome = forage.act(move.x, move.y, move.ccw);
        const where = `move ${i}`;
        expect(outcome, where).toBe(move.outcome);
        if (outcome === 'moved') {
          expect(forage.lastResult.points, where).toBe(move.points);
          expect(forage.lastResult.combo, where).toBe(move.combo);
        }
        expect([forage.board.crates, forage.board.crateArea, forage.board.bonusMode, forage.cratesCollected], where).toEqual([
          move.crates,
          move.area,
          move.pending,
          move.collected,
        ]);
        if (move.board) expect(forage.cells, where).toEqual(move.board);
      });
    });
  }
});

/** A board from rows of letters: 0-4 fruit, S M K E tools,. empty. */
function boardOf(rows: string[], seed = 1): Forage {
  const game = new Forage(seed);
  const tools: Record<string, number> = { S: 5, M: 6, K: 7, E: 8, '.': -1 };
  const cells = rows.flatMap((row) => [...row].map((ch) => tools[ch] ?? Number(ch)));
  game.load(cells);
  return game;
}

/** Rows that never line up three of a kind. */
const QUIET = ['0123401', '2340123', '4012340', '1234012', '3401234', '0123401', '2340123', '4012340', '1234012', '3401234'];

describe('Forage rules', () => {
  it('turns any 2x2 of pieces, match or not; left click anticlockwise', () => {
    const g = boardOf(QUIET);
    expect(g.act(0, 0, true)).toBe('moved');
    // Anticlockwise: top-right to top-left, top-left down to bottom-left.
    expect([g.board.getPiece(0, 0), g.board.getPiece(1, 0), g.board.getPiece(0, 1), g.board.getPiece(1, 1)]).toEqual([1, 3, 0, 2]);
  });

  it("won't turn a 2x2 with a tool, crate or gap in it", () => {
    const g = boardOf(['S' + QUIET[0].slice(1), ...QUIET.slice(1)]);
    expect(g.board.isLegalRotate(0, 0)).toBe(false);
    g.board.setPiece(0, 0, makeCrate(0, 0, 0));
    expect(g.board.isLegalRotate(0, 0)).toBe(false);
    g.board.setPiece(0, 0, -1);
    expect(g.board.isLegalRotate(0, 0)).toBe(false);
  });

  it('counts runs separately for the combo, and scores nothing for fruit', () => {
    // A plus: one run across and one down through the same cell.
    const g = boardOf(QUIET);
    for (const [x, y] of [
      [1, 4],
      [2, 4],
      [3, 4],
      [2, 3],
      [2, 5],
    ])
      g.board.setPiece(x, y, 0);
    expect(g.board.findRuns().length).toBe(2);
  });

  it('scores crates by width squared, more for each crate in the same step and each later step', () => {
    const p = new CratePoints();
    expect([p.crate(1), p.crate(2), p.crate(3)]).toEqual([1, 8, 36]);
    p.endStep();
    expect(p.crate(2)).toBe(6);
    p.endStep();
    expect(p.crate(1)).toBe(2);
    p.endStep();
    expect(p.chained).toBe(3);
  });

  it('sends ants a step each move and starves them at the edge', () => {
    const g = boardOf(QUIET);
    g.board.setPiece(3, 8, makeAnts(8, 3));
    g.act(0, 0, true);
    expect(g.board.cells.filter((p) => (p & 0xff) === 9).length).toBe(1);
    // They ate the piece below and moved down, one fewer.
    expect(g.board.getPiece(3, 9)).toBe(makeAnts(7, 3));
    g.act(0, 0, true);
    expect(g.board.antsOnBoard()).toBe(false);
  });

  it('takes 85ms a row to fall and 250ms to turn', () => {
    expect(TIMING.fall(1)).toBe(85);
    expect(TIMING.turn).toBe(250);
    expect(TIMING.antStep).toBe(256);
  });

  it('only ever puts specials in refills after runs', () => {
    const board = new ForageBoard(5n, 8);
    for (let i = 0; i < 500; i++) expect(board.getNextPiece()).toBeLessThan(5);
    board.setComboCount(8);
    let specials = 0;
    for (let i = 0; i < 2000; i++) if (board.getNextPiece() >= 5) specials++;
    // 13% at a combo of 8.
    expect(specials / 2000).toBeGreaterThan(0.09);
    expect(specials / 2000).toBeLessThan(0.17);
  });

  it('fills a 7x10 board with no three in a row', () => {
    const board = new ForageBoard(123n);
    expect(board.findRuns()).toEqual([]);
    expect(board.cells.length).toBe(WIDTH * HEIGHT);
  });
});
